spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service # service name
          predicates:
            - Path=/user-service/** # url pattern

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file-service/**

        - id: post-reply-service
          uri: lb://post-reply-service
          predicates:
            - Path=/post-reply-service/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message-service/**

        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/history-service/**

        - id: post-composite-service
          uri: lb://post-composite-service
          predicates:
            - Path=/post-composite-service/**

        - id: user-composite-service
          uri: lb://user-composite-service
          predicates:
            - Path=/user-composite-service/**

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/**

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
